---
title: "My Page"
---

## My GitHub page

<https://github.com/adamiturabi>

## My projects

Here is a list of some of my projects:

* [_A Grammar of Standard Classical Arabic_](https://adamiturabi.github.io/arabic-tutorial-book/)  
  This is an online book, rendered using [Quarto](https://quarto.org/), that aims to teach students Standard Classical Arabic.
  It is a work in progress.
* [Minimum(ish) Working Example of Quarto with Arabic RTL text in an LTR document](https://adamiturabi.github.io/quarto-arabic-mwe)
* [Hava Arabic Dictionary digitization project ](https://adamiturabi.github.io/hava-dig)  
  (work in progress)

## Interesting research topics

Here are some research topics that I find interesting.
I'm not sure I have the training to undertake them but I would be interested in reading dissertations/books/papers on them:

1. How did Classical Arabic express existential "There is a ..." sentences? For example,

   + "There is a god."
   + "There is a heaven and there is a hell."

   MSA uses هناك and the modern vernaculars use various words like في، است, etc.

   Synchonically, how did Classical Arabic speakers get around it? What did the إسناد (مسند, مسند إليه) of such a sentence look like?

   Diachronically, was أَيْسَ used ubiquituously and then it became disused? Is it a congnate of Hebrew YESH (יֵשׁ)? What were the causes of Arabic losing أَيس , not needing an existential for a while, and then developing the existential في?

   Some relevant material:

   1. Khalid Said, "Existential Constructions in Classical Arabic and the Reduction of Deicticity in Modern Standard Arabic: A Comparative Study" <https://www.academia.edu/94158819/>
   2. Allahem, K. S., Alharbi, B. Y. (2023). On the Syntax of Existential Sentences in Standard Arabic. WORD, 69(2), 137–159. <https://doi.org/10.1080/00437956.2023.2202603>

2. A unifying model that encapsulates تقدير, عمل, اشتغال and solves some of the problematic areas where عمل doesn't seem fulfilling. Can we bring dependency grammar into the picture without throwing out عمل?

If you have any links to material on these topics, feel welcome to open a discussions thread here:
<https://github.com/adamiturabi/arabic-tutorial-book/discussions>

## Curated list of online books

Here is a list of online books with interesting design and good typesetting, that I have found:

+ [Butterick's _Practical Typography_](https://practicaltypography.com/)  
  Subject: Typography
+ [_The Art of Chance_ by Dennis Sun, Gene Kim, and Anav Sood](https://dlsun.github.io/skis/)  
  Subject: Probability
+ [_Interactive Linear Algebra_ by Dan Margalit, Joseph Rabinoff](https://textbooks.math.gatech.edu/ila/)  
  Subject: Linear Algebra
+ [_Introduction to Modern Statistics_ by Mine Çetinkaya-Rundel and Johanna Hardin](https://openintro-ims.netlify.app/)  
  Subject: Statistics
+ [_MathNotes_](https://math-website.pages.dev/)  
  Subject: Math

